name: CI

on: 
  push:
    paths:
    - 'src/*'
    - 'dub.json'
    - '.github/workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: apt-get install -yq gcc dmd ldc dub
    - name: Run dub test
      run: dub test
