name: CI

on: 
  push:
    paths:
    - 'src/*'
    - 'dub.json'
    - '.github/workflows/*'

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo snap install --classic dmd dub
    - name: Run dub test
      run: dub test
